export class BackgroundLibrary {
    constructor() {
        this.background1 = [
          [
            { tileIndex: 6, type: " walkable" },
            { tileIndex: 6, type: "walkable" },
            { tileIndex: 6, type: "walkable" },
            { tileIndex: 6, type: "walkable" },
            { tileIndex: 6, type: "walkable" },
            { tileIndex: 6, type: "walkable" },
            { tileIndex: 6, type: "walkable" },
            { tileIndex: 6, type: "walkable" },
            { tileIndex: 6, type: "walkable" },
            { tileIndex: 6, type: "walkable" },
            { tileIndex: 6, type: "walkable" },
            { tileIndex: 6, type: "walkable" },
            { tileIndex: 6, type: "walkable" },
          ],
          [
            { tileIndex: 6, type: "walkable" },
            { tileIndex: 0, type: "walkable" },
            { tileIndex: 1, type: "walkable" },
            { tileIndex: 2, type: "walkable" },
            { tileIndex: 6, type: "walkable" },
            { tileIndex: 6, type: "walkable" },
            { tileIndex: 6, type: "walkable" },
            { tileIndex: 6, type: "walkable" },
            { tileIndex: 6, type: "walkable" },
            { tileIndex: 6, type: "walkable" },
            { tileIndex: 6, type: "walkable" },
            { tileIndex: 6, type: "walkable" },
            { tileIndex: 6, type: "walkable" },
          ],
          [
            { tileIndex: 1, type: "walkable" },
            { tileIndex: 19, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 15, type: "walkable" },
            { tileIndex: 6, type: "walkable" },
            { tileIndex: 6, type: "walkable" },
            { tileIndex: 6, type: "walkable" },
            { tileIndex: 6, type: "walkable" },
            { tileIndex: 6, type: "walkable" },
            { tileIndex: 6, type: "walkable" },
            { tileIndex: 6, type: "walkable" },
            { tileIndex: 6, type: "walkable" },
            { tileIndex: 6, type: "walkable" },
          ],
          [
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "not_walkable", overlayIndex: 48 },
            { tileIndex: 14, type: "not_walkable", overlayIndex: 49 },
            { tileIndex: 20, type: "walkable" },
            { tileIndex: 1, type: "walkable" },
            { tileIndex: 1, type: "walkable" },
            { tileIndex: 1, type: "walkable" },
            { tileIndex: 1, type: "walkable" },
            { tileIndex: 1, type: "walkable" },
            { tileIndex: 1, type: "walkable" },
            { tileIndex: 1, type: "walkable" },
            { tileIndex: 1, type: "walkable" },
            { tileIndex: 1, type: "walkable" },
          ],
          [
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "not_walkable", overlayIndex: 61 },
            { tileIndex: 14, type: "not_walkable", overlayIndex: 62 },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
          ],
          [
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "not_walkable", overlayIndex: 10 },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
          ],
          [
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
          ],
          [
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "not_walkable", overlayIndex: 10 },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
          ],
          [
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 16, type: "walkable" },
            { tileIndex: 17, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
          ],
          [
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 29, type: "walkable" },
            { tileIndex: 30, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
          ],
          [
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
          ],
          [
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
          ],
          [
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
          ],
        ];  
        
        this.background2 = [
          [
            { tileIndex: 3, type: " walkable" },
            { tileIndex: 6, type: "walkable" },
            { tileIndex: 6, type: "walkable" },
            { tileIndex: 6, type: "walkable" },
            { tileIndex: 6, type: "walkable" },
            { tileIndex: 6, type: "walkable" },
            { tileIndex: 6, type: "walkable" },
            { tileIndex: 6, type: "walkable" },
            { tileIndex: 6, type: "walkable" },
            { tileIndex: 6, type: "walkable" },
            { tileIndex: 6, type: "walkable" },
            { tileIndex: 6, type: "walkable" },
            { tileIndex: 6, type: "walkable" },
          ],
          [
            { tileIndex: 6, type: "walkable" },
            { tileIndex: 0, type: "walkable" },
            { tileIndex: 1, type: "walkable" },
            { tileIndex: 2, type: "walkable" },
            { tileIndex: 6, type: "walkable" },
            { tileIndex: 6, type: "walkable" },
            { tileIndex: 6, type: "walkable" },
            { tileIndex: 6, type: "walkable" },
            { tileIndex: 6, type: "walkable" },
            { tileIndex: 6, type: "walkable" },
            { tileIndex: 6, type: "walkable" },
            { tileIndex: 6, type: "walkable" },
            { tileIndex: 6, type: "walkable" },
          ],
          [
            { tileIndex: 1, type: "walkable" },
            { tileIndex: 19, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 15, type: "walkable" },
            { tileIndex: 6, type: "walkable" },
            { tileIndex: 6, type: "walkable" },
            { tileIndex: 6, type: "walkable" },
            { tileIndex: 6, type: "walkable" },
            { tileIndex: 6, type: "walkable" },
            { tileIndex: 6, type: "walkable" },
            { tileIndex: 6, type: "walkable" },
            { tileIndex: 6, type: "walkable" },
            { tileIndex: 6, type: "walkable" },
          ],
          [
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "not_walkable", overlayIndex: 48 },
            { tileIndex: 14, type: "not_walkable", overlayIndex: 49 },
            { tileIndex: 20, type: "walkable" },
            { tileIndex: 1, type: "walkable" },
            { tileIndex: 1, type: "walkable" },
            { tileIndex: 1, type: "walkable" },
            { tileIndex: 1, type: "walkable" },
            { tileIndex: 1, type: "walkable" },
            { tileIndex: 1, type: "walkable" },
            { tileIndex: 1, type: "walkable" },
            { tileIndex: 1, type: "walkable" },
            { tileIndex: 1, type: "walkable" },
          ],
          [
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "not_walkable", overlayIndex: 61 },
            { tileIndex: 14, type: "not_walkable", overlayIndex: 62 },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
          ],
          [
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "not_walkable", overlayIndex: 10 },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
          ],
          [
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
          ],
          [
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "not_walkable", overlayIndex: 10 },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
          ],
          [
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 16, type: "walkable" },
            { tileIndex: 17, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
          ],
          [
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 29, type: "walkable" },
            { tileIndex: 30, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
          ],
          [
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
          ],
          [
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
          ],
          [
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
            { tileIndex: 14, type: "walkable" },
          ],
        ];
        }
  }